"""unique_value_for_songs.title

Revision ID: 17816f4a7263
Revises: 629feaf2bcc7
Create Date: 2025-05-07 13:43:39.371695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17816f4a7263"
down_revision: Union[str, None] = "629feaf2bcc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_songs_title", "songs", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_songs_title", "songs", type_="unique")
    # ### end Alembic commands ###
