"""add children variant to song_type enum

Revision ID: a48f27bf14c7
Revises: bf1caac39c54
Create Date: 2025-11-02 23:22:13.823901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "a48f27bf14c7"
down_revision: Union[str, None] = "bf1caac39c54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="songtype",
        new_values=["universal", "male", "female", "duet", "children"],
        affected_columns=[TableReference(table_schema="public", table_name="songs", column_name="type")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="songtype",
        new_values=["universal", "male", "female", "duet"],
        affected_columns=[TableReference(table_schema="public", table_name="songs", column_name="type")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
