"""add_file_type_to_songs

Revision ID: bf1caac39c54
Revises: 17816f4a7263
Create Date: 2025-08-06 21:56:29.872288

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bf1caac39c54"
down_revision: Union[str, None] = "17816f4a7263"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("video", "audio", name="filetype").create(op.get_bind())
    op.add_column(
        "songs",
        sa.Column(
            "file_type",
            postgresql.ENUM("video", "audio", name="filetype", create_type=False),
            nullable=True,
            server_default="video",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("songs", "file_type")
    sa.Enum("video", "audio", name="filetype").drop(op.get_bind())
    # ### end Alembic commands ###
